### ISSUE TITLE
Show the pdf directly to potential employers using github pages

### ISSUE THREAD

**Issue by DilecPadovani** [Spinny03/resume#1]
Save the compiled PDF into the repo and enable GitHub Pages for this project. Then create an index.html page and set the page to be linked to this file from settings. 
In the file, you should put this HTML:
``` html
<iframe src="https://yourusername.github.io/repository/path_to_pdf.pdf" width="100%" height="500px">
</iframe>
```
By doing so, people that are interested in your job can view your resume without having to download the file, and you can directly share the URL of this web page.

**Comment by Spinny03** [comment]
Thanks mate, I'll implement your suggestions as soon as I can
